### ISSUE TITLE
Types for using in Typescript based projects

### ISSUE THREAD

**Issue by aislanmaia** [easyroute-router/svelte-easyroute#31]
This router have any package we can install from to get typing ?

Importing anything from 'svelte-easyroute' eslint warning about not found types for it.

**Comment by lyohaplotinka** [comment]
Hi @aislanmaia! 
Types for Svelte components are my headache :)
I'm working on it. Hopefully it will be fixed soon.

**Comment by Sajjon** [comment]
Any TypeScript support update? :)

**Comment by lyohaplotinka** [comment]
Hi @aislanmaia, @Sajjon!
Glad to tell you that support for TypeScript is here, in v3.1.1 :)
